---
# tasks file for deploy_fail2ban

- name: Check and Print LINUX Version
  debug: var=ansible_os_family

- block:     # ======Block for REDHAT======

  - name: Install fail2ban for RedHat
    become: yes
    yum:
      name: "{{ fail2ban_ver_for_fedora }}"     # fail2ban-1.0.2-12.fc39
      update_cache: yes
    notify:
      - Start and enable fail2ban service

  when: ansible_os_family == "RedHat"

- block:     # ======Block for UBUNTU======

  - name: Install fail2ban for Ubuntu
    become: yes
    apt:
      name: "{{ fail2ban_ver_for_ubuntu }}"      # fail2ban=0.11.2-6
      update_cache: yes
    notify:
      - Start and enable fail2ban service

  when: ansible_os_family == "Debian"


- name: Write jail.local file with var
  become: yes
  template:
    src: jail.j2
    dest: "{{ destin_files }}/jail.local"
    mode: 0555
  notify:
      - Restart fail2ban service
