---
# Tasks file for fail2ban

- include_tasks: install_for_redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: install_for_debian.yml
  when: ansible_os_family == "Debian"

- name: Write jail.local file with var
  become: yes
  template:
    src: jail.j2
    dest: /etc/fail2ban/jail.local
    mode: 0555
  notify:
      - Reload fail2ban service
